version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.0
    container_name: elasticsearch
    environment:
      - node.name=es01
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data 
    ports:
      - 9200:9200
    networks:
      - elk
    restart: unless-stopped
  kibana:
    image: docker.elastic.co/kibana/kibana:8.2.0
    container_name: kibana
    environment:
      - "SERVER_NAME=kib01.alban"
      - "ELASTICSEARCH_HOSTS=http://elasticsearch:9200"
    ports:
      - 5601:5601
    networks:
      - elk
    restart: unless-stopped
  logstash:
    image: docker.elastic.co/logstash/logstash:8.2.0
    container_name: logstash
    ports:
      - 5000:5000
    environment:
      - "NODE_NAME=log01"
      - "PATH_DATA=/data"
    volumes:  
      - type: bind
        source: ./conf/logstash/pipeline
        target: /usr/share/logstash/pipeline
      - type: bind
        source: ./data/logstash
        target: /data
      - type: bind
        source: /var/log/suricata/eve.json
        target: /var/log/eve.json
    networks:
      - elk
    restart: unless-stopped
volumes:
  esdata01:
    driver: local
networks:
  elk:
    driver: bridge